.Dd May 26, 2017
.Dt LIBSANDBOX 3
.Sh NAME
.Nm libsandbox 
.Nd sandbox library definitions
.Sh SYNOPSIS
.In sandbox.h
.Ft int
.Fn sandbox "const char *script" "int flags"
.Ft int
.Fn sandbox_from_file "const char *path" "int flags"
.Ft int
.Fn sandbox_pledge "const char *promises" "const char *paths[]"
.Sh DESCRIPTION
.Sh AUTHORS
.An Stephen Herwig Aq Mt smherwig@cs.umd.edu
